### ISSUE TITLE
turtlebot2 not working with ros2 and ros kinetic

### ISSUE THREAD

**Issue by sagniknitr** [ros2/turtlebot2_demo#64] opened 2017-09-14 09:01 UTC
OS- Ubuntu 14.04

Error- Due to presence of "amcl" packages, I am facing issues in installing turltebot2 in ubuntu 16.04 OS having ROS Kinetic and ros2 installed.

**Comment by clalancette** [comment] 2017-09-14 13:54
We've only tested the turtlebot demo stuff on Ubuntu 16.04.  It may work on newer things, but we don't plan on supporting something as old as Ubuntu 14.04.

In the future, please make sure to fill out the issue template, otherwise it is hard to figure out what the problem is without error messages.  I'm going to close this out; feel free to reopen if you still have problems with a newer Ubuntu.

**Comment by mikaelarguedas** [comment] 2017-09-14 14:51
I think 14.04 was a typo, given that Ros kinetic is not available on trusty.

> I am facing issues in installing turltebot2 in ubuntu 16.04 OS having ROS Kinetic and ros2 installed.

This says 16.04.

**Comment by dirk-thomas** [comment] 2017-09-14 14:57
The request for more information is still relevant. Please provide the information requested in the issue template. As-is the description doesn't have enough details to act on.

**Comment by mikaelarguedas** [comment] 2017-09-14 15:00
@sagniknitr, can you confirm if you are using Ubuntu 14.04 or 16.04 ? 

Note that the only Linux version the ROS 2 project targets and is tested for is Ubuntu Xenial (16.04).


Could you also provide all the information listed in the issue template (such as what version of ros2 you are using, installation type etc) ?

Thanks!

**Comment by mikaelarguedas** [comment] 2017-10-16 15:20
Closing this due to no response, @sagniknitr feel free to comment here with more details and we can reopen this issue

**Closed as completed by mikaelarguedas** 2017-10-16 15:20 UTC
Labels: more-information-needed
